{
    "name": "greenBEAR Procurement",
    "version": "19.0.0.4.3",
    "category": "Operations/Purchase",
    "summary": "Prototype for traceable procurement and pre-commitment control",
    "depends": ["base", "base_import_module", "base_automation", "purchase", "account", "mail"],
    "data": [
        "models/dimensions.xml",
        "models/model_registry.xml",
        "models/budget.xml",
        "models/procurement.xml",
        "security/security_groups.xml",
        "data/sequence_automation.xml",
        "data/budget_actions.xml",
        "data/workflow_actions.xml",
        "security/ir.model.access.csv",
        "views/dimension_views.xml",
        "views/procurement_views.xml",
        "views/budget_views.xml",
        "views/purchase_order_views.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
